# Generated by Django 5.1 on 2024-09-03 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('outlet', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outlet',
            name='email',
        ),
        migrations.RemoveField(
            model_name='outlet',
            name='phoneNumber',
        ),
    ]
