# Generated by Django 5.1 on 2024-09-17 06:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0001_initial'),
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='phoneNumber',
            new_name='phone_number',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='customer',
        ),
        migrations.AddField(
            model_name='customer',
            name='club_points',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customer',
            name='name',
            field=models.CharField(default=1, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='customer_profile', to='auths.userprofile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='wishlist',
            field=models.TextField(blank=True, null=True),
        ),
    ]
