# Generated by Django 5.1 on 2024-09-26 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_shippingaddress_city_shippingaddress_state_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingaddress',
            name='address',
            field=models.TextField(),
        ),
    ]
