# Generated by Django 5.1 on 2024-09-17 07:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0001_initial'),
        ('customer', '0003_remove_shippingaddress_phone_number_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='phoneNumber',
            new_name='phone_number',
        ),
        migrations.AlterField(
            model_name='customer',
            name='club_points',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='customer',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer', to='auths.userprofile'),
        ),
    ]
