# Generated by Django 5.1 on 2024-08-31 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('customer', 'Customer'), ('outlet_manager', 'Outlet Manager')], default='customer', max_length=50),
        ),
        migrations.AddField(
            model_name='customer',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('customer', 'Customer'), ('outlet_manager', 'Outlet Manager')], default='customer', max_length=50),
        ),
        migrations.AddField(
            model_name='outletmanager',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('customer', 'Customer'), ('outlet_manager', 'Outlet Manager')], default='customer', max_length=50),
        ),
    ]
