# Generated by Django 5.1 on 2024-08-31 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0002_adminuser_role_customer_role_outletmanager_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminuser',
            name='role',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='role',
        ),
        migrations.RemoveField(
            model_name='outletmanager',
            name='role',
        ),
    ]
