# Generated by Django 5.1 on 2024-09-18 16:04

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
        ('products', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Enter the coupon code.', max_length=50, unique=True)),
                ('coupon_amount', models.DecimalField(decimal_places=2, help_text='Discount amount', max_digits=10)),
                ('allow_free_shipping', models.BooleanField(default=False, help_text='Allow free shipping?')),
                ('coupon_expiry', models.DateField(blank=True, help_text='Expiry date of the coupon', null=True)),
                ('minimum_spend', models.DecimalField(blank=True, decimal_places=2, help_text='Minimum spend to apply coupon', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('maximum_spend', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum spend to apply coupon', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('individual_use_only', models.BooleanField(default=False, help_text='If true, coupon cannot be used with other coupons.')),
                ('exclude_sale_items', models.BooleanField(default=False, help_text='Exclude items on sale?')),
                ('usage_limit_per_coupon', models.PositiveIntegerField(blank=True, help_text='Max number of times this coupon can be used in total', null=True)),
                ('usage_limit_per_user', models.PositiveIntegerField(blank=True, help_text='Max number of times a user can use this coupon', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('blocked_accounts', models.ManyToManyField(blank=True, help_text='Users who cannot use this coupon', to=settings.AUTH_USER_MODEL)),
                ('excluded_categories', models.ManyToManyField(blank=True, help_text='Categories to exclude', related_name='excluded_discounts', to='category.category')),
                ('excluded_products', models.ManyToManyField(blank=True, help_text='Products excluded from coupon usage', to='products.product')),
                ('included_categories', models.ManyToManyField(blank=True, help_text='Categories to include', related_name='included_discounts', to='category.category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discounts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
