# Generated by Django 5.1 on 2024-10-19 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='coupon_expiry_time',
            field=models.DateTimeField(blank=True, help_text='Expiry date and time of the coupon', null=True),
        ),
    ]
