# Generated by Django 5.1 on 2024-10-21 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0002_discount_coupon_expiry_time'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='included_products',
            field=models.ManyToManyField(blank=True, help_text='Products included in coupon usage', related_name='included_products', to='products.product'),
        ),
    ]
