# Generated by Django 5.1 on 2024-09-16 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auths', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderId', models.CharField(max_length=255, unique=True)),
                ('orderTime', models.DateTimeField(auto_now_add=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('origin', models.CharField(max_length=255)),
                ('orderStatus', models.CharField(choices=[('Pending Payment', 'Pending Payment'), ('Processing', 'Processing'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled'), ('Failed', 'Failed')], default='Pending Payment', max_length=50)),
                ('status', models.BooleanField(default=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='auths.userprofile')),
            ],
        ),
    ]
