# Generated by Django 5.1 on 2024-09-16 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customerName',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='customerPhoneNumber',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
    ]
