# Generated by Django 5.1 on 2024-10-07 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cash_on_delivery', 'Cash on Delivery'), ('digital_payment', 'Digital Payment')], default='cash_on_delivery', max_length=20),
        ),
    ]
