# Generated by Django 5.1 on 2024-09-16 16:52

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_order_customername_order_customerphonenumber'),
        ('products', '0003_alter_product_weight'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='customerName',
        ),
        migrations.RemoveField(
            model_name='order',
            name='customerPhoneNumber',
        ),
        migrations.RemoveField(
            model_name='order',
            name='orderStatus',
        ),
        migrations.RemoveField(
            model_name='order',
            name='origin',
        ),
        migrations.AlterField(
            model_name='order',
            name='orderId',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='orderTime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Payment'), ('processing', 'Processing'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='order.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(related_name='orders', through='order.OrderItem', to='products.product'),
        ),
    ]
