# Generated by Django 5.1 on 2024-09-17 10:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_alter_customer_club_points_alter_customer_user'),
        ('order', '0002_order_shippingaddress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='shippingAddress',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='customer.customer'),
        ),
    ]
