# Generated by Django 5.1 on 2024-09-26 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_order_coupon_code_order_discount_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='shippingAddress',
            new_name='shipping_address',
        ),
        migrations.RemoveField(
            model_name='order',
            name='discount_amount',
        ),
    ]
