# Generated by Django 5.1 on 2024-09-18 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='featureImage',
            field=models.ImageField(blank=True, null=True, upload_to='features/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='productsGallery',
            field=models.ImageField(blank=True, null=True, upload_to='gallery/'),
        ),
    ]
