# Generated by Django 5.1 on 2024-09-20 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.CharField(default=1, max_length=100, verbose_name='Color'),
            preserve_default=False,
        ),
    ]
