# Generated by Django 5.1 on 2024-09-08 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='dimension_height',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Height (cm)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='dimension_length',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Length (cm)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='dimension_width',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Width (cm)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='weight',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
