# Generated by Django 5.1 on 2024-09-25 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_product_featureimage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='featureImage',
            field=models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Feature Image'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image_type',
            field=models.CharField(choices=[('gallery', 'Gallery Image')], default='gallery', max_length=20),
        ),
    ]
