# Generated by Django 5.1 on 2024-09-18 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_featureimage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='featureImage',
            field=models.ImageField(default=1, upload_to='features'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='productsGallery',
            field=models.ImageField(default=1, upload_to='gallery'),
            preserve_default=False,
        ),
    ]
