# Generated by Django 5.1 on 2024-09-18 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_featureimage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='featureImage',
            field=models.ImageField(blank=True, null=True, upload_to='features'),
        ),
        migrations.AlterField(
            model_name='product',
            name='productsGallery',
            field=models.ImageField(blank=True, null=True, upload_to='gallery'),
        ),
        migrations.AlterField(
            model_name='product',
            name='weight',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Weight (kg)'),
        ),
    ]
